bin_PROGRAMS = shell
shell_SOURCES = shell.c feature1.c feature2.c feature3.c feature4.c feature5.c
shell_HEADERS = feature1.h feature2.h feature3.h feature4.h feature5.h
shelldir = ./

clean-local:
	@rm config.status configure config.log
	@rm Makefile
	@rm -r autom4te.cache/
	@rm aclocal.m4
	@rm compile install-sh missing Makefile.in
	@rm -r .deps/
	@rm depcomp
